name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: Team-Sellora/.github/.github/workflows/reusable-ci.yml@main
    with:
      solution-path: Sellora.CoreService.sln
      sonar-project-key: Team-Sellora_sellora-organization
      sonar-organization: team-sellora
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}